import Head from "next/head";
import styled from "styled-components";
import { useEffect, useState } from "react";

export default function Home() {
  const [state, setState] = useState({ data: "" });

  useEffect(() => {
    getData();
    async function getData() {
      const response = await fetch("/api/data-for-react");
      const data = await response.json();
      setState(data);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>My NextJS App {state.data}</h1>
      </Main>
    </div>
  );
}

const Main = styled.main`
  text-align: center;
`;
